### ISSUE TITLE
[Proposal] make topcoder-react-utils a single devDependency

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/topcoder-react-utils#2]
Don't know where is better to write a proposal, so I create an issue. let me know if there is a better place.

Currently, if we want to use the same building process for another project we have to run `adopt-dev-deps` which will update our `package.json` with all the `devDependecies` and after we have to write webpack config files which will merge some configs from the `topcoder-react-utils`. What do you think about making `topcoder-react-utils` work similar way to [react-scripts](https://github.com/facebook/create-react-app/tree/next/packages/react-scripts) 
   - So instead of copying all the dependencies, our project has only one devDependency `topcoder-react-utils` and provides some commands like `build`, `start`, `dev`, `lint` and so on.
   - The benefits of such approach are:
     - `topcoder-react-utils` could be theoretically used as a bootstrap during challenges. If it works the way `react-scripts` then it would be very handy to use, as there are zero lines to write before starting coding.
     - updating `devDependencies` will become centralized. Don't have to run `adopt-dev-deps` again.
   -  Downside:
      - Have to think how to handle situations if a project needs to make some modifications to config files. Not sure if there is a good solution. In `react-scripts` we only can run `eject` command in such case, which will copy all the files from `react-scripts` to the project. So in this case, we would loose benefits of `react-scripts` as we cannot use it anymore.
      - Probably we can have some folders in the project which will extend corresponding configs from `topcoder-react-utils`.

**Comment by birdofpreyru** [comment]
@maxceem I am sure open to discussion, as I am learning a lot about NPM as I have started to work on this, and may miss something. Here are my current thoughts on this:

1.  Regarding dependencies management.

    - `topcoder-react-utils` should be prod dependency, because it (will) contains lots of code necessary at runtime.

    - Copying of `topcoder-react-utils`'s dev dependencies into the host package is required as otherwise they are not installed by `npm install`, while we still need them if we want to build the host package using the same babel/webpack configs. Prod dependencies of `topcoder-react-utils`, if they are directly used by the host package, also should be installed into the host package explicitly (no need for a special script, because it is anyway tested and enforced by ESLint). The reason for this is that there is `npm link` command, which allows, for dev purposes, to install a package from a local folder instead of the global NPM repo. If you `npm link` a package *A* into package *B* then all dependencies of *A* are installed into `node_modules` inside the local folder of *A*, and they are not installed into `node_modules` inside the folder of *B*, which would break *B* if all dependencies are not explicitely listed in its `package.json`. I am not sure, though, whether `npm link` is useful for us at all, cause it seems to break Webpack build process when a part of config comes from a linked package (we need to experiment more with it).

2.  Regarding the usage of `topcoder-react-utils` for bootstrapping.

    - My idea is to have `topcoder-react-utils` as a collection of general-purpose re-usable code, and for bootstrapping of ReactJS apps to create a few starting packs, based on `topcoder-react-utils`. I am saying a few, cause I already see a few different use-cases, all of which still need the same pieces of code from `topcoder-react-utils`:

      - Building additional ReactJS libraries, like [topcoder-react-ui-kit](https://github.com/topcoder-platform/topcoder-react-ui-kit), where we gonna move any styles / component themes following TC styleguide, i.e. what we need only for TC platform projects;

      - Building of big ReactJS apps, like Community App, Connect App, etc.; where we want use Redux, server-side rendering, and other stuff that takes more efforts to use, but helps to structure and maintain a long-term projects with big codebase;

      - Building light ReactJS apps, like a few screens promo website, etc.; which we want to create as fast as possible, and it won't have too complex/large code, neither will be actively evolving once created. In this case we don't need Redux, server-side rendering, etc.; although we still want to use CSS modules and some other stuff.

      So, I believe, once `topcoder-react-utils` is somewhat stable and tested with Community App and Connect App, we can create and maintain starting packs for these purposes.
