### ISSUE TITLE
Cannot find module 'postcss-scss'

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/topcoder-react-utils#3]
What I did:
1. add dependencies using `adopt-dev-deps topcoder-react-utils`
2. use production webpack config `topcoder-react-utils/config/webpack/app-production`
3. getting error `Cannot find module 'postcss-scss'`

Probably dependency `postcss-scss` can to be moved from https://github.com/topcoder-platform/community-app/blob/develop/package.json#L68 to `topcoder-react-utils`.

**Comment by birdofpreyru** [comment]
You are right, I'll add `postcss-scss` as dev dependency of `topcoder-react-utils` in my next commit. Before that, you can just install it as a dev dependency of Connect App (as we anyway copy dev deps from `topcoder-react-utils` into host packages, we'll anyway need to do it).
