### ISSUE TITLE
configFactory: support entry as an array

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/topcoder-react-utils#6]
Providing `entry` value to `configFactory` as an `array` it's not supported.

What I did:
- Call `configFactory` providing an array to `entry`:
   ```
   configFactory({
     entry: [
       'one entry',
       'second entry'
     ]
   })
   ```
- In the resulting webpack config both for `development` and `production` environment I get:
   ```
   {
      entry: [
       'one entry',
       'second entry'
     ]
   }
   ```

- Expected output for production is:
   ```
   {
     entry: {
       main: [
         'one entry',
         'second entry'
       ],
       polyfills, [
         'babel-polyfill',
         'nodelist-foreach-polyfill',
      ]
  }
   ```

- and for development:
   ```
   {
     entry: {
       main: [
         'react-hot-loader/patch',
         'webpack-hot-middleware/client?reload=true',
         'one entry',
         'second entry'
       ],
       polyfills, [
         'babel-polyfill',
         'nodelist-foreach-polyfill',
      ]
  }
   ```

**Comment by birdofpreyru** [comment]
@maxceem are you sure you don't override the entry config at your side, ocasionally?
Cause the code block that normalizes the entry config (https://github.com/topcoder-platform/topcoder-react-utils/blob/0d262074e91014341ea8191eaca4237d0b96d5a9/config/webpack/app-base.js#L63) is supposed to support array values already.

**Comment by birdofpreyru** [comment]
Oh... Let's replace it with `_.isPlainObject(..)`? It will work correct for this case. Can you think about any corner case where it may fail?

**Comment by maxceem** [comment]
Replacing with `_.isPlainObject(..)` sounds like a proper solution. I cannot imagine any reasonable value where it can fail.
