### ISSUE TITLE
[Enhancement] include lodash method per function instead of the whole lib

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/topcoder-react-utils#7]
Currently, we are trying to reduce the bundle size of `connect app` https://github.com/appirio-tech/connect-app/issues/1629

One of the steps is avoid including the whole `lodash` library as
`import _ from 'lodash'`
in favour of including only necessary methods as following
`import omit from 'lodash'`

As `topcoder-react-utils` has become a dependency of `connect app` it would be great if it also follows the same practice as otherwise, it will bring the whole `lodash` lib to the bundle if we use `GenericLink` in `connect app`.

I see only one place where `lodash` is invoked in `topcoder-react-utils` https://github.com/topcoder-platform/topcoder-react-utils/blob/master/src/shared/components/GenericLink.jsx#L11

**Comment by maxceem** [comment]
I've found a more elegant solution. Just use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) which do the same automatically.

As `topcoder-react-utils` is being pre-built to publish in `npm` probably this plugin has to used during the building process to make an affect.

**Comment by birdofpreyru** [comment]
@maxceem the full build of lodash is just 72.8 kb; when I see at the Community App, it is just a drop among the entire volume of the generated code, I believe it makes no sense to care about it.

Anyway, neither `topcoder-react-utils`, nor `topcoder-react-ui-kit` bundle external dependencies into the code bundles they produce, they rely that those packages will be provided by the final host app, it is configured here:
https://github.com/topcoder-platform/topcoder-react-utils/blob/master/config/webpack/lib-base.js#L36-L48

So, if you still like to play with that with use of the plugin, I guess you can do it purely at Connect App side.
